# This is a basic workflow to help you get started with Actions

name: Make PDF

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install pandoc and latex
        run: sudo apt install pandoc pandoc-citeproc texlive texlive-lang-japanese texlive-luatex texlive-fonts-extra latexmk ruby
      
      - name: Convert Markdwon to PDF (with LuaLaTeX)
        run: rake
        
      - name: Upload generated PDF as artifact
        uses: actions/upload-artifact@v2
        with:
          name: generated_PDF
          path: README.pdf
